sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: qK/S1oEfLd04/tXx1iiPSL29VAQrDaYtLkfQipipQxMdRpG/mKe54MO9ipCQzpC+mJ996/I12jTokIHbklhOPbmMSeX49TlG1zsmgXydNtKQiVb2eU+8Ga1ezbik5JpQMs6a65b0v0or4kXJrZUfjyJ56rVU7HCaAx19SXu+nhC5XmcE+NiWEJSodWZshDx0sfbBT+Z+6BbjdrqZxs+rIEkRNgz5uI56+aYXeirP0dRUQ71Wp6/X7S8+5wr31tiNUMEEzmxuwbqYTUpDBIq1TgF/r38QuMxSlpwJnFY8IJ8KnERTpHi7eM/dUfPialD80eo/dxMHLBwrcil7YwHjVoLrJjesZtbyoAakHeNXf4txmBw39qH84yZNEvrOw/56kpnbCei079+4PEazQ+vb/ruh/935bnu0JdFoSPR49hwNtVMifY7+2G1K3+VSrnDozZlmFrolcYGZcNSUq0RHMEep1gW9uKe1kBJDAFWoV7l/VO3gyqQNf+PwEKG68XjBtbxjuxzhBkF2yV2BPCquKOf+0aN/VEJrHaV++fs3eUJoaKRT3hLY2+alR15PsfwFLBUWiX5dQsNWlV1W9HMvQ8YKNeFKMPGKzjvsWK1faxTszkK916MdlP1BnpJPf80iiJ3r/8GM1BiAhWxSuXibT7q/Pu9q2PqBa0SMUoBEerc=
branches:
  only:
  - master
