sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
  - secure: ji+xUiOgcxm6sJSk1vGuzTShs1yYylFcjT/GKtW3T9vmzSJn4Wq61/ltHPlM3YyLzvVt1UFSP+JBX+I/dJpYrc75Xm4UIn2uUTyJ2A73ruovyU6GvxtPVuUcFWYrCFNge57CdOD866o4gRODTXqNz6niyLXnr0KPSv4T/+sePGltGTbTLh7fX6m80k2FyTAwXqJZYz35y3e3dotquge5JGX4tyM+Y9qJC/Dllhy1DMudQzA3vmiOrgwkqdQNAwxKfSqw+dxMpZ2BoaUCh/h3qPV2lw17sGXnKzQUScN10ELyS96YBR3BO9Yty/AXumRsrRyt/s10eXR7Gh/KYUnoJ6cEt6sXHNAOb3S0rGvJjdiO/uZfP9tJnK1v6cocOO8IuZvNtdfwidH4Qev3jqeWMYHHRBdqTT3xCNEKtNw8Jbg56a1Pu7lAl67k6GHnrGTAbuS0hKbjJFbj8MUH3IrnJxlEB7q7T+SuER0bNvkQbdQ+Suap5AKWUy/yrfWTln7iWtXggNvSRxDnj90BwvFlXgq6AuYPwleX3VjFlwEHMHfGWurgXOFnuLF+71rgdRfPPNqitCluZPBwEf9hIklKFw1p8oHyA7DrmFd4bH2E10xyXSfcaWvEQAP1cjFJuQgQqeAt6S8/vA9UhcNeykxXS2ttLjnpCjPNvgm4i4yg7tw=
