sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
  - secure: Tikunvi4EjbNOtl5D3QH3yoRW+4TwxDPgSTzN1biLiAOpMJgov0lIgANmU5aQEcztMR+zl1ex3qlNZg4oOM6em/bP2GEcwG4y5maw30gskS/tGax2KYdCDRp89TmjX4m0pl1fPjV6+AXnmrUgIs0rHRbXucdRbQn7TEk4L4VOEmvl/kuvBlhx/UqbmkPlsYglpl+gotgUJA7K1R+HKINZRqT0ORBgd1wj48Eph2ibPpxTK4rCAOLIvCaiLD2nFysV0QFos3Scnj8EAqCsbzLt/+dW4m8YL1lwgzAFYnP8s9NQgBV8//oQPZ+T7KSIwTL5gHEBdRExP5s/t5tBEmrOnWPvTKra3ZcWajYWmc6Qe2aUztv2gzO6GF2dn0iyUOkaeE28AlQ9ear+J/KStzyVrIp2e/n3OooE9T9J9f5FyFgmvFebIqu3icK20zqPpXVblkmYxv6ayEDqowb+bTs6tADYBGNDrEEvm/l8Rt+3q80OoNVuuR5b/0jvGnUP0coL6CRRVipbAPJuqifbOjYNeBPE8xtoJw8LO0oXBgL84blgWwY/TljqVsS5WLnooJ0J0wnsd/m6p3m7o3gswIungch+VUkrP34hD+bTRmf0zqPj9UG116vXjpPIj0/j550/xOVlph4MeJjieuYhQmDIhjgQQVhHmJp5fFk/RR5WJU=
